# Generated by Django 4.2.3 on 2023-07-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='breed',
            new_name='species',
        ),
    ]
